export const INIT_GAMES = 'INIT_GAMES';

export const FETCH_GAMES_REQUEST = 'GAMES_REQUEST';
export const GAMES_REQUEST_SUCCESS = 'GAMES_REQUEST_SUCCESS';
export const GAMES_REQUEST_FAILD = 'GAMES_REQUEST_FAILD';
